package pmotor;
import Sql.koneksisql;
import Controler.dbtransaksi;
import java.sql.Connection;
import java.sql.Statement;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;
import java.sql.ResultSet;
import java.text.MessageFormat;
import javax.swing.JTable;

public class Transaksi extends javax.swing.JFrame {                                                                             //i
    ResultSet rs ;
    PreparedStatement pst ;
    dbtransaksi a = new dbtransaksi();
    
    public Transaksi() {
        initComponents();
        setLocationRelativeTo(null);
        tampil_combo();
        clear();
    }
        public void loadtabel(){
        try {
            tabeltransaksi.setModel(DbUtils.resultSetToTableModel(a.UpdateJTable()));
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        Textnama = new javax.swing.JTextField();
        Textnohp = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Textalamat = new javax.swing.JTextArea();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        Textmerek = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        Texttipe = new javax.swing.JTextField();
        ButtonBayar = new javax.swing.JButton();
        Comboidmotor = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabeltransaksi = new javax.swing.JTable();
        btnhapus = new javax.swing.JButton();
        Btnprint = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        TextHarga = new javax.swing.JTextField();
        BtnClear = new javax.swing.JButton();
        ComboStatus = new javax.swing.JComboBox<>();
        Btnedit = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        TextStatus = new javax.swing.JTextField();
        CBTersedia = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 153, 255));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pmotor/img/motorbike.png"))); // NOI18N
        jButton1.setText("Home");
        jButton1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jButton1FocusLost(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pmotor/img/man.png"))); // NOI18N
        jButton2.setText("Data Motor");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pmotor/img/transaction.png"))); // NOI18N
        jButton3.setText("Transaksi");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pmotor/img/log-out.png"))); // NOI18N
        jButton4.setText("Log Out");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(80, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3)
                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 520, 950, 100));

        jPanel3.setBackground(new java.awt.Color(0, 153, 204));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("Nama");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 80, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("Nomor HP");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 120, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 250, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setText("Alamat");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 160, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 210, -1, -1));

        Textnama.setMinimumSize(new java.awt.Dimension(200, 29));
        Textnama.setPreferredSize(new java.awt.Dimension(200, 29));
        Textnama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextnamaActionPerformed(evt);
            }
        });
        jPanel3.add(Textnama, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 80, 200, -1));

        Textnohp.setMinimumSize(new java.awt.Dimension(200, 29));
        Textnohp.setPreferredSize(new java.awt.Dimension(200, 29));
        jPanel3.add(Textnohp, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 120, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel7.setText("Transaksi");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        Textalamat.setColumns(20);
        Textalamat.setRows(5);
        jScrollPane1.setViewportView(Textalamat);

        jPanel3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 160, 200, 70));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel8.setText("ID Motor");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, -1, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel10.setText("Merek");
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, -1, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel11.setText("Tipe");
        jPanel3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, -1, -1));

        Textmerek.setEditable(false);
        Textmerek.setMinimumSize(new java.awt.Dimension(200, 29));
        Textmerek.setPreferredSize(new java.awt.Dimension(200, 29));
        Textmerek.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextmerekActionPerformed(evt);
            }
        });
        jPanel3.add(Textmerek, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 120, -1, -1));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel12.setText("Status Motor");
        jPanel3.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, -1, -1));

        Texttipe.setEditable(false);
        Texttipe.setMinimumSize(new java.awt.Dimension(200, 29));
        Texttipe.setPreferredSize(new java.awt.Dimension(200, 29));
        jPanel3.add(Texttipe, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 160, -1, -1));

        ButtonBayar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pmotor/img/wallet.png"))); // NOI18N
        ButtonBayar.setText("Bayar");
        ButtonBayar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonBayarActionPerformed(evt);
            }
        });
        jPanel3.add(ButtonBayar, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 280, 120, 40));

        Comboidmotor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboidmotorActionPerformed(evt);
            }
        });
        jPanel3.add(Comboidmotor, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 80, 200, 30));

        tabeltransaksi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID Motor", "Nama", "No Hp", "Alamat", "Status Pembayaran"
            }
        ));
        tabeltransaksi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabeltransaksiMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tabeltransaksi);

        jPanel3.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 390, 930, 120));

        btnhapus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pmotor/img/delete.png"))); // NOI18N
        btnhapus.setText("Hapus");
        btnhapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhapusActionPerformed(evt);
            }
        });
        jPanel3.add(btnhapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 340, -1, -1));

        Btnprint.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pmotor/img/printer.png"))); // NOI18N
        Btnprint.setText("Cetak Tabel Transaksi");
        Btnprint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnprintActionPerformed(evt);
            }
        });
        jPanel3.add(Btnprint, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 10, 200, 40));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel13.setText("Total Harga");
        jPanel3.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, -1, -1));

        TextHarga.setEditable(false);
        TextHarga.setMinimumSize(new java.awt.Dimension(200, 29));
        TextHarga.setPreferredSize(new java.awt.Dimension(200, 29));
        jPanel3.add(TextHarga, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 200, -1, -1));

        BtnClear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pmotor/img/cleaning.png"))); // NOI18N
        BtnClear.setText("Clear");
        BtnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnClearActionPerformed(evt);
            }
        });
        jPanel3.add(BtnClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 340, -1, -1));

        ComboStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cash", "Kredit" }));
        ComboStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboStatusActionPerformed(evt);
            }
        });
        jPanel3.add(ComboStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 240, 200, 30));

        Btnedit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pmotor/img/updated.png"))); // NOI18N
        Btnedit.setText("Edit");
        Btnedit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtneditActionPerformed(evt);
            }
        });
        jPanel3.add(Btnedit, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 340, -1, -1));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel14.setText("Pembayaran");
        jPanel3.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 240, -1, -1));

        TextStatus.setEditable(false);
        TextStatus.setMinimumSize(new java.awt.Dimension(200, 29));
        TextStatus.setPreferredSize(new java.awt.Dimension(200, 29));
        TextStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextStatusActionPerformed(evt);
            }
        });
        jPanel3.add(TextStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 240, -1, -1));

        CBTersedia.setText("Tersedia");
        CBTersedia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBTersediaActionPerformed(evt);
            }
        });
        jPanel3.add(CBTersedia, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 280, -1, -1));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 950, 520));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    public void tampil_combo()
    {
        try {
        Connection con = koneksisql.getKoneksi();
        Statement stt = con.createStatement();
        String sql = "select idmotor from motordb order by idmotor asc";
        ResultSet res = stt.executeQuery(sql);                             
        
        while(res.next()){
            Object[] ob = new Object[1];
            ob[0] = res.getString(1);
            
           Comboidmotor.addItem((String) ob[0]);
        }
        res.close(); stt.close();
         
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }  
    public void tampil()
    {
        try {
        Connection con = koneksisql.getKoneksi();
        Statement stt = con.createStatement();
        String sql = "select merek,harga,tipe,tersedia from motordb where idmotor='"+Comboidmotor.getSelectedItem()+"'";  
        ResultSet res = stt.executeQuery(sql);
        
        while(res.next()){
            Object[] ob = new Object[4];
            ob[0]=  res.getString(1);
            ob[1]=  res.getString(2);
            ob[2]=  res.getString(3);
            ob[3]=  res.getString(4);
            
            Textmerek.setText((String) ob[0]);
            TextHarga.setText((String) ob[1]);
            Texttipe.setText((String) ob[2]);
            TextStatus.setText((String) ob[3]);
        }
        res.close(); stt.close();
         
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }
       public void clear(){
       Comboidmotor.setSelectedItem("");
       Textnama.setText("");
       Textnohp.setText("");
       ComboStatus.setSelectedItem("");
       Textalamat.setText("");
    }
    public void deklarasi(){
        a.idmotor = Comboidmotor.getSelectedItem().toString();
        a.totalharga = TextHarga.getText();
        a.nama = Textnama.getText();
        a.nomorhp = Textnohp.getText();
        a.alamat = Textalamat.getText();
        a.statuspembayaran = ComboStatus.getSelectedItem().toString();
        a.tersedia = TextStatus.getText();
    }
    private void jButton1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jButton1FocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1FocusLost

    private void TextmerekActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextmerekActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextmerekActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.setVisible(false);
        new Home().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.setVisible(false);
        new Data_Motor().setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        this.setVisible(false);
        new Login().setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        loadtabel();
    }//GEN-LAST:event_formWindowOpened

    private void ButtonBayarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonBayarActionPerformed
       String ObjBtn[]={"ya","tidak"};
       int PromptResult = JOptionPane.showOptionDialog(null,"data sudah benar?","Message",JOptionPane.DEFAULT_OPTION,JOptionPane.QUESTION_MESSAGE,null, ObjBtn, ObjBtn[1]);
       if (PromptResult==0) {
        deklarasi();
        try {
        a.simpan();
        a.ubah();
        JOptionPane.showMessageDialog(null, "data telah tersimpan");
        clear();
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }loadtabel();
    }//GEN-LAST:event_ButtonBayarActionPerformed
    }
    
    private void tabeltransaksiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabeltransaksiMouseClicked
        int row = tabeltransaksi.getSelectedRow();
        Comboidmotor.setSelectedItem(tabeltransaksi.getModel().getValueAt(row, 0).toString());
        TextHarga.setText(tabeltransaksi.getModel().getValueAt(row, 1).toString());
        Textnama.setText(tabeltransaksi.getModel().getValueAt(row, 2).toString());
        Textnohp.setText(tabeltransaksi.getModel().getValueAt(row, 3).toString());
        Textalamat.setText(tabeltransaksi.getModel().getValueAt(row, 4).toString());
        ComboStatus.setSelectedItem(tabeltransaksi.getModel().getValueAt(row, 5).toString());
    }//GEN-LAST:event_tabeltransaksiMouseClicked

    private void btnhapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhapusActionPerformed
       String ObjBtn[]={"ya","tidak"};
       int PromptResult = JOptionPane.showOptionDialog(null,"hapus data?","Message",JOptionPane.DEFAULT_OPTION,JOptionPane.QUESTION_MESSAGE,null, ObjBtn, ObjBtn[1]);
        if (PromptResult==0) {
            deklarasi();
            try {
                a.hapus();
                loadtabel();
                clear();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            }
        }
    }//GEN-LAST:event_btnhapusActionPerformed

    private void BtnprintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnprintActionPerformed
        try {
            tabeltransaksi.print(JTable.PrintMode.FIT_WIDTH,new MessageFormat("Tabel Transaksi"),null);
        } catch (java.awt.print.PrinterException e) {
            System.err.format("Printer tidak terdeteksi", e.getMessage());
        }
    }//GEN-LAST:event_BtnprintActionPerformed

    private void ComboidmotorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboidmotorActionPerformed
        tampil();
    }//GEN-LAST:event_ComboidmotorActionPerformed

    private void BtnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnClearActionPerformed
        clear();
    }//GEN-LAST:event_BtnClearActionPerformed

    private void ComboStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboStatusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboStatusActionPerformed

    private void TextnamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextnamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextnamaActionPerformed

    private void BtneditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtneditActionPerformed
        deklarasi();
        try {
            a.edit();
            a.ubah();
            JOptionPane.showMessageDialog(null, "berhasil diubah");
            loadtabel();
            clear();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }

    }//GEN-LAST:event_BtneditActionPerformed

    private void TextStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextStatusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextStatusActionPerformed

    private void CBTersediaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBTersediaActionPerformed
    if (CBTersedia.isSelected()){
        TextStatus.setText("Terjual");
    }
    else {TextStatus.setText("Tersedia");
    }
    }//GEN-LAST:event_CBTersediaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Transaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Transaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Transaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Transaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Transaksi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnClear;
    private javax.swing.JButton Btnedit;
    private javax.swing.JButton Btnprint;
    private javax.swing.JButton ButtonBayar;
    private javax.swing.JCheckBox CBTersedia;
    private javax.swing.JComboBox<String> ComboStatus;
    public javax.swing.JComboBox<String> Comboidmotor;
    public javax.swing.JTextField TextHarga;
    public javax.swing.JTextField TextStatus;
    private javax.swing.JTextArea Textalamat;
    public javax.swing.JTextField Textmerek;
    private javax.swing.JTextField Textnama;
    private javax.swing.JTextField Textnohp;
    public javax.swing.JTextField Texttipe;
    private javax.swing.JButton btnhapus;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable tabeltransaksi;
    // End of variables declaration//GEN-END:variables
}
